modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="parched_lands"
version="1.0.1"
displayName="Parched Lands"
authors="Nakanishi"

description='''${mod_description}'''
[[dependencies.parched_lands]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.parched_lands]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"